export const types = {
  uiToggleSidebarMobile: "[ui] Toggle Sidebar Mobile",
  uiStartLoadingAllSlides: "[ui] Start Loading AllSlides",
  uiStartLoadingAllProducts: "[ui] Start Loading AllProducts",
  uiStopLoadingAllProducts: "[ui] Stop Loading AllProducts",
  uiStartLoadingProductsSections: "[ui] Start Loading All Products Sections",
  uiStopLoadingProductsSections: "[ui] Stop Loading All Products Sections",
  uiStartAddMoreAllSlides: "[ui] Start Add More AllSlides",
  uiStopAddMoreAllSlides: "[ui] Stop Add More AllSlides",
  uiStopLoadingAllSlides: "[ui] Stop Loading AllSlides",
  uiStartLoadingCurrentSlides: "[ui] Start Loading CurrentSlides",
  uiStopLoadingCurrentSlides: "[ui] Stop Loading CurrentSlides",
  uiStartCreateProduct: "[ui] Start Create Product",
  uiStopCreateProduct: "[ui] Stop Create Product",
  uiStartAddProductsSection: "[ui] Start Add Products Section",
  uiStopAddProductsSection: "[ui] Stop Add Products Section",
  uiStartSearchingProducts: "[ui] Start Searching Products",
  uiStopSearchingProducts: "[ui] Stop Searching Products",
  uiStartCreateUser: "[ui] Start Create User",
  uiStopCreateUser: "[ui] Stop Create User",

  slideLoadAllSlides: "[slides] Load All Slides",
  slideAddMoreAllSlides: "[slides] Add More All Slides",
  slideUpload: "[slides] Upload Slide",
  slideAddToCurrentSlides: "[slides] Add To Current Slides",
  slideLoadCurrentSlides: "[slides] Load Current Slide",
  slideDelete: "[slides] Delete Slide",

  authStartRegister: "[auth] Start Register",
  authEndRegister: "[auth] End Register",
  authStartLogin: "[auth] Start Login",
  authEndLogin: "[auth] End Login",

  productsLoadAllproducts: "[products] Load All Products",
  productsDeleteAllProducts: "[products] Delete All Products",
  productCreateProduct: "[products] Create Product",
  productAddProductsSection: "[products] Add Products Section",
  productsLoadProductsSections: "[products] Load All Products Sections",
  productsSearchProducts: "[products] Search Products",

  usersLoadAllusers: "[users] Load All Users",
  usersCreateUser: "[users] Create User",
};
