export const data = [
  {	
  	id: 1,
    sku: "1",
    name: "pedraza",
    price: 9,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "2",
    name: "pedraza",
    price: 6,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "3",
    name: "pedraza",
    price: 4,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "gaston",
    name: "rodriguez",
    price: 2,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "gaston",
    name: "rodriguez",
    price: 2,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "gaston",
    name: "rodriguez",
    price: 1,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "esteban",
    name: "rodriguez",
    price: 9,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "esteban",
    name: "rodriguez",
    price: 9,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "esteban",
    name: "rodriguez",
    price: 9,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "esteban",
    name: "pedraza",
    price: 7,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "esteban",
    name: "pedraza",
    price: 9,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "esteban",
    name: "pedraza",
    price: 5,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "esteban",
    name: "pedraza",
    price: 9,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "gaston",
    name: "pedraza",
    price: 9,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "gaston",
    name: "pedraza",
    price: 6,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "gaston",
    name: "pedraza",
    price: 4,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "gaston",
    name: "rodriguez",
    price: 2,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "gaston",
    name: "rodriguez",
    price: 2,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "gaston",
    name: "rodriguez",
    price: 1,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "esteban",
    name: "rodriguez",
    price: 9,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "esteban",
    name: "rodriguez",
    price: 9,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "esteban",
    name: "rodriguez",
    price: 9,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "esteban",
    name: "pedraza",
    price: 7,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "esteban",
    name: "pedraza",
    price: 9,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "esteban",
    name: "pedraza",
    price: 5,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "esteban",
    name: "pedraza",
    price: 9,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "gaston",
    name: "pedraza",
    price: 9,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "gaston",
    name: "pedraza",
    price: 6,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "gaston",
    name: "pedraza",
    price: 4,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "gaston",
    name: "rodriguez",
    price: 2,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "gaston",
    name: "rodriguez",
    price: 2,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "gaston",
    name: "rodriguez",
    price: 1,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "esteban",
    name: "rodriguez",
    price: 9,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "esteban",
    name: "rodriguez",
    price: 9,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "esteban",
    name: "rodriguez",
    price: 9,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "esteban",
    name: "pedraza",
    price: 7,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "esteban",
    name: "pedraza",
    price: 9,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "esteban",
    name: "pedraza",
    price: 5,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "esteban",
    name: "pedraza",
    price: 9,
    description: "some text here",
    category: "smartphones",
    stock: 6,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "gaston",
    name: "pedraza",
    price: 9,
    description: "some text here",
    category: "smartphones",
    stock: 4,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "gaston",
    name: "pedraza",
    price: 6,
    description: "some text here",
    category: "smartphones",
    stock: 4,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "gaston",
    name: "pedraza",
    price: 4,
    description: "some text here",
    category: "smartphones",
    stock: 4,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  },
  {	
  	id: 1,
    sku: "gaston",
    name: "rodriguez",
    price: 2,
    description: "some text here",
    category: "smartphones",
    stock: 4,
    state: "acitvo",
    createdAt: JSON.stringify(new Date()),
    updatedAt: JSON.stringify(new Date()),
  }
];